config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :registered_applications

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  get 'landing/index'

  root 'landing#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events

  validates :name, length: { minimum: 3, maximum: 254 }, presence: true, uniqueness: { case_sensitive: false }
  validates :url, length: {minimum: 4, maximum: 254 }, presence: true, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :registered_applications

  before_save { self.role ||= :member }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  enum role: [:admin, :member]
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def preflight
    head 200
  end

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if registered_application == nil
      render json: "Unregistered application", status: :unprocessable_entity

    end

    @event = Event.new(event_params)
    @event.registered_application = registered_application
    
    if @event.save
      render json: @event, status: :created
    else
      render json: {errors: @event.errors}, status: :unprocessable_entity
    end
  end


  private
  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @apps = current_user.registered_applications
    authorize @apps
  end

  def show
    @app = RegisteredApplication.find(params[:id])
    authorize @app
    @events = @app.events.group_by(&:name)
    @event_count = @app.events.group_by(&:id).count
  end

  def new
    @app = RegisteredApplication.new
    @user = current_user
  end

  def create
    @app = RegisteredApplication.new(app_params)
    @app.user = current_user
    authorize @app

    if @app.save
      flash[:notice] = "Application was saved."
      redirect_to registered_applications_path
    else
      flash.now[:alert] = "There was an error saving the application."
    end
  end

  def edit
    @app = RegisteredApplication.find(params[:id])
    @app.user = current_user
    authorize @app
  end

  def update
    @app = RegisteredApplication.find(params[:id])
    @app.assign_attributes(app_params)
    authorize @app

    if @app.save
      flash[:notice] = "Application was saved."
      redirect_to registered_applications_path
    else
      # flash.now[:alert] = "There was an error saving the application."
      render :edit
    end
  end


  def destroy
    @app = RegisteredApplication.find(params[:id])

    if @app.destroy
      flash[:notice] = "App was deleted."
      redirect_to registered_applications_path
    else
      flash.now[:alert] = "There was an error removing the application."
    end
  end


  private

  def app_params
    params.require(:registered_application).permit(:name, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << 'has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/views/landing/index.html.erb
<div class="container-fluid">

  <% if current_user %>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">TrackMetrics</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="<%= registered_applications_path %>">MyApps <span class="sr-only">(current)</span></a></li>
          <li><a href="<%= new_registered_application_path %>">Add App</a></li>
        </ul>
      </div>
    </nav>
  <% end %>


  <% if current_user == nil %>
    <div class="jumbotron jumbotron-fluid jumbotron-landing-nil">
      <div class="container-fluid">
        <center><h1>TrackMetrics</h1></center>
        <center><h2>Track activity on the web.</h2></center>
      </div>
    </div>
  <% else %>
    <div class="jumbotron jumbotron-fluid jumbotron-landing">
      <div class="container-fluid">
        <center><h1>TrackMetrics</h1></center>
        <center><h2>Track activity on the web.</h2></center>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="assets/woman1.png" alt="woman eating salad">
        <div class="caption">
          <h3>Track your friends.</h3>
            <p>Julia buys hemorrhoid cream?</p>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="assets/woman2.png" alt="woman eating another salad">
        <div class="caption">
          <h3>Track your family.</h3>
            <p>Spoiler: they all watch kink porn.</p>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="assets/woman3.png" alt="last woman eating salad">
        <div class="caption">
          <h3>Track your co-workers.</h3>
            <p>Show 'em who's boss of their privacy.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <% if current_user == nil %>
      <center><h1><a href="<%= new_user_registration_path %>">Sign up </a>and start tracking today!</h1></center>
    <% end %>
  </div>

</div>

app/views/landing/index2.html.erb
<h1>Landing#index</h1>
<p>Find me in app/views/landing/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trackmetrics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<script>blocmetrics.report('about page loaded');</script>
<body>
  <div class="container">
    <div class="nav nav-tabs">
      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong> |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
  </div>

  <div class="container">
    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>

  </div>
</body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for app do |f| %>
  <% if app.errors.any? %>
    <div class="alert alert-danger">
      <h4>There were <%= pluralize(app.errors.count, "error") %> with your request:</h4>
      <ul>
        <% app.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= form_group_tag(app.errors[:name]) do %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "Enter app name" %>
    <% end %>
    <%= form_group_tag(app.errors[:url]) do %>
      <%= f.label :url %>
      <%= f.text_field :url, rows: 1, class: 'form-control', placeholder: "Please enter a full URL (https://example.com)" %>
    <% end %>
    <br>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
      <%= link_to "Cancel", registered_applications_path, class: 'btn btn-info' %>
      <div class="right-side">
        <% if @app.id %>
          <%= link_to "Delete App", [@app], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this app?  This can not be undone!'} %>
        <% end %>
      </div>
    </div>
<% end %>

app/views/registered_applications/edit.html.erb
<h1>Edit App Info</h1>

<div class="container">
  <div class="row">
    <div class="col-md-11">
        <%= render partial: 'form', locals: { app: @app, user: @user } %>
    </div>
  </div>
</div>

app/views/registered_applications/index.html.erb
<div class="container-fluid">

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">TrackMetrics</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="<%= registered_applications_path %>">MyApps <span class="sr-only">(current)</span></a></li>
          <li><a href="<%= new_registered_application_path %>">Add App</a></li>
        </ul>
      </div>
    </nav>


  <div class="jumbotron">
    <center><h1>Registered Applications</h1></center>
  </div>
  <div class="row">
    <div class="col-md-11">
      <%= link_to "Add Application", new_registered_application_path, class: 'btn-group btn-success btn-sm' %>
    </div>
  </div>


  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">URL</th>
        <th scope="col">Unique ID</th>
      </tr>
    </thead>

    <% @apps.each_with_index do |app, index| %>
      <tr>
        <th scope="row"> <%= index + 1 %> </th>
        <td> <%= link_to app.name, registered_application_path(app.id) %> </td>
        <td> <%= link_to app.url, registered_application_path(app.id) %> </td>
        <td> <%= link_to app.id, registered_application_path(app.id) %> </td>
      </tr>
    <% end %>

</div>

app/views/registered_applications/new.html.erb
<h1>Add An App</h1>

<div class="row">
  <div class="col-md-11">
    <div class="col-md-11">
      <%= render partial: 'form', locals: { app: @app, user: @user } %>
    </div>
  </div>
</div>

app/views/registered_applications/show.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

<div class="container-fluid">

  <nav class="navbar navbar-default navbar-show">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">TrackMetrics</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= registered_applications_path %>">MyApps <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= edit_registered_application_path %>">Edit This App</a></li>
      </ul>
    </div>
  </nav>


  <div>
    <%= pie_chart @app.events.group(:name).count %>
  </div>
  <div>
    <%= line_chart @app.events.group_by_day(:created_at).count %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">URL</th>
        <th scope="col">Event Names</th>
        <th scope="col">Event Count</th>
      </tr>
    </thead>

    <tr>
      <td> <%= @app.name %> </td>
      <td> <%= @app.url %> </td>
      <td>
          <% @events.each do |key, value| %>
            <%= key + "." %>
          <% end %>
      </td>
      <td>
        <%= @event_count %>
      </td>
    </tr>
</div>